// "use strict";

// module.exports = {
//   up: async (queryInterface, Sequelize) => {
//     await queryInterface.bulkInsert("Playerdetails", [
//             {
//   FirstName: "Jonas",
//   LastName: "Neubauer",
//   Alias: "Jonas",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Jeff",
//   LastName: "Moore",
//   Alias: "Jeff",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "TX",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Harry",
//   LastName: "Hong",
//   Alias: "Harry",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Sean",
//   LastName: "Ritchie",
//   Alias: "Quaid",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Alex",
//   LastName: "Kerr",
//   Alias: "Alex",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Bo",
//   LastName: "Steil",
//   Alias: "Bo",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Matt",
//   LastName: "Buco",
//   Alias: "Buco",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Terry",
//   LastName: "Purcell",
//   Alias: "Terry",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Chad",
//   LastName: "Muse",
//   Alias: "Chad",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Jani",
//   LastName: "Herlevi",
//   Alias: "Jani",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "FI",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Chris",
//   LastName: "Brady",
//   Alias: "Chris",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Joey",
//   LastName: "Parker",
//   Alias: "Joey",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Mike",
//   LastName: "Winzinek",
//   Alias: "Mike",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "David",
//   LastName: "Vulich",
//   Alias: "David",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Peter",
//   LastName: "Grisafi",
//   Alias: "Peter",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Matt",
//   LastName: "Schoolmaster",
//   Alias: "Schoolmaster",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Dana",
//   LastName: "Wilcox",
//   Alias: "Dana",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Cameron",
//   LastName: "Eure",
//   Alias: "Cameron",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Vince",
//   LastName: "Clement",
//   Alias: "Vince",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Trey",
//   LastName: "Harrison",
//   Alias: "Trey",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Danny",
//   LastName: "Vulich",
//   Alias: "Danny",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Frank",
//   LastName: "Westphal",
//   Alias: "Frank",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Robin",
//   LastName: "Mihara",
//   Alias: "Robin",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Chris",
//   LastName: "Extine",
//   Alias: "Chris",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Rigel",
//   LastName: "Pearce",
//   Alias: "Rigel",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Adam",
//   LastName: "Cornelius",
//   Alias: "Adam",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Steve",
//   LastName: "Hugnes",
//   Alias: "Steve",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Gin",
//   LastName: "Morgan",
//   Alias: "Gin",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Ryan",
//   LastName: "Ritchie",
//   Alias: "Ryan",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Jason",
//   LastName: "Simoneaux",
//   Alias: "Jason",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Brian",
//   LastName: "Glessner",
//   Alias: "Brian",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
// {
//   FirstName: "Kim",
//   LastName: "Arceo",
//   Alias: "Kim",
//   Birthdate: "1981-04-19 0:00:00",
//   Country: "USA",
//   State: "CA",
//   Playstyle: "DAS",
//   HideName: false,
// },
//     ]);
//   },

//   async down(queryInterface, Sequelize) {
//     await queryInterface.bulkDelete("Playerdetails", null, {});
//     /**
//      * Add commands to revert seed here.
//      *
//      * Example:
//      * await queryInterface.bulkDelete('People', null, {});
//      */
//   },
// };
