INSERT INTO matches (DateTime, Local_Time ,Timezone,BestOf,Player1ID,Player1Score,Player2ID,Player2Score,WinnerID,LoserID,Version,Live,Completed,EventID,Draw)
VALUES

('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Alex Kerr"),2,(SELECT ID FROM playerdetails WHERE Alias = "Kim Arceo"),0,(SELECT ID FROM playerdetails WHERE Alias = "Alex Kerr"),(SELECT ID FROM playerdetails WHERE Alias = "Kim Arceo"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2016-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Joey"),2,(SELECT ID FROM playerdetails WHERE Alias = "Danny Vulich"),0,(SELECT ID FROM playerdetails WHERE Alias = "Joey"),(SELECT ID FROM playerdetails WHERE Alias = "Danny Vulich"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Chad Muse"),2,(SELECT ID FROM playerdetails WHERE Alias = "Vince Clemente"),1,(SELECT ID FROM playerdetails WHERE Alias = "Chad Muse"),(SELECT ID FROM playerdetails WHERE Alias = "Vince Clemente"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Chris Brady"),2,(SELECT ID FROM playerdetails WHERE Alias = "Jason Simoneaux"),0,(SELECT ID FROM playerdetails WHERE Alias = "Chris Brady"),(SELECT ID FROM playerdetails WHERE Alias = "Jason Simoneaux"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Jonas Neubauer"),2,(SELECT ID FROM playerdetails WHERE Alias = "Robin Mihara"),0,(SELECT ID FROM playerdetails WHERE Alias = "Jonas Neubauer"),(SELECT ID FROM playerdetails WHERE Alias = "Robin Mihara"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Dana Wilcox"),1,(SELECT ID FROM playerdetails WHERE Alias = "Peter Grisafi"),2,(SELECT ID FROM playerdetails WHERE Alias = "Peter Grisafi"),(SELECT ID FROM playerdetails WHERE Alias = "Dana Wilcox"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "David Vulich"),2,(SELECT ID FROM playerdetails WHERE Alias = "Frank Westphal"),0,(SELECT ID FROM playerdetails WHERE Alias = "David Vulich"),(SELECT ID FROM playerdetails WHERE Alias = "Frank Westphal"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Terry Purcell"),2,(SELECT ID FROM playerdetails WHERE Alias = "Steve Hugnes"),0,(SELECT ID FROM playerdetails WHERE Alias = "Terry Purcell"),(SELECT ID FROM playerdetails WHERE Alias = "Steve Hugnes"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Harry Hong"),2,(SELECT ID FROM playerdetails WHERE Alias = "Brian Glessner"),0,(SELECT ID FROM playerdetails WHERE Alias = "Harry Hong"),(SELECT ID FROM playerdetails WHERE Alias = "Brian Glessner"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Trey Harrison"),0,(SELECT ID FROM playerdetails WHERE Alias = "Mike Winzinek"),2,(SELECT ID FROM playerdetails WHERE Alias = "Mike Winzinek"),(SELECT ID FROM playerdetails WHERE Alias = "Trey Harrison"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Matt Buco"),2,(SELECT ID FROM playerdetails WHERE Alias = "Gin Morgan"),0,(SELECT ID FROM playerdetails WHERE Alias = "Matt Buco"),(SELECT ID FROM playerdetails WHERE Alias = "Gin Morgan"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Jeff Moore"),2,(SELECT ID FROM playerdetails WHERE Alias = "Chris Extine"),0,(SELECT ID FROM playerdetails WHERE Alias = "Jeff Moore"),(SELECT ID FROM playerdetails WHERE Alias = "Chris Extine"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Bo Steil"),2,(SELECT ID FROM playerdetails WHERE Alias = "Ryan Ritchie"),0,(SELECT ID FROM playerdetails WHERE Alias = "Bo Steil"),(SELECT ID FROM playerdetails WHERE Alias = "Ryan Ritchie"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Cameron Eure"),1,(SELECT ID FROM playerdetails WHERE Alias = "Schoolmaster"),2,(SELECT ID FROM playerdetails WHERE Alias = "Schoolmaster"),(SELECT ID FROM playerdetails WHERE Alias = "Cameron Eure"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Jani Herlevi"),2,(SELECT ID FROM playerdetails WHERE Alias = "Rigel Pearce"),0,(SELECT ID FROM playerdetails WHERE Alias = "Jani Herlevi"),(SELECT ID FROM playerdetails WHERE Alias = "Rigel Pearce"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Quaid"),2,(SELECT ID FROM playerdetails WHERE Alias = "Adam Cornelius"),0,(SELECT ID FROM playerdetails WHERE Alias = "Quaid"),(SELECT ID FROM playerdetails WHERE Alias = "Adam Cornelius"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),



('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Alex Kerr"),2,(SELECT ID FROM playerdetails WHERE Alias = "Joey"),0,(SELECT ID FROM playerdetails WHERE Alias = "Alex Kerr"),(SELECT ID FROM playerdetails WHERE Alias = "Joey"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Chris Brady"),1,(SELECT ID FROM playerdetails WHERE Alias = "Chad Muse"),2,(SELECT ID FROM playerdetails WHERE Alias = "Chad Muse"),(SELECT ID FROM playerdetails WHERE Alias = "Chris Brady"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Jonas Neubauer"),2,(SELECT ID FROM playerdetails WHERE Alias = "Peter Grisafi"),0,(SELECT ID FROM playerdetails WHERE Alias = "Jonas Neubauer"),(SELECT ID FROM playerdetails WHERE Alias = "Peter Grisafi"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "David Vulich"),0,(SELECT ID FROM playerdetails WHERE Alias = "Terry Purcell"),2,(SELECT ID FROM playerdetails WHERE Alias = "David Vulich"),(SELECT ID FROM playerdetails WHERE Alias = "Terry Purcell"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Harry Hong"),2,(SELECT ID FROM playerdetails WHERE Alias = "Mike Winzinek"),0,(SELECT ID FROM playerdetails WHERE Alias = "Harry Hong"),(SELECT ID FROM playerdetails WHERE Alias = "Mike Winzinek"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Jeff Moore"),0,(SELECT ID FROM playerdetails WHERE Alias = "Matt Buco"),2,(SELECT ID FROM playerdetails WHERE Alias = "Matt Buco"),(SELECT ID FROM playerdetails WHERE Alias = "Jeff Moore"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Bo Steil"),2,(SELECT ID FROM playerdetails WHERE Alias = "Schoolmaster"),0,(SELECT ID FROM playerdetails WHERE Alias = "Bo Steil"),(SELECT ID FROM playerdetails WHERE Alias = "Schoolmaster"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Jani Herlevi"),0,(SELECT ID FROM playerdetails WHERE Alias = "Quaid"),2,(SELECT ID FROM playerdetails WHERE Alias = "Quaid"),(SELECT ID FROM playerdetails WHERE Alias = "Jani Herlevi"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),


('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Alex Kerr"),2,(SELECT ID FROM playerdetails WHERE Alias = "Chad Muse"),0,(SELECT ID FROM playerdetails WHERE Alias = "Alex Kerr"),(SELECT ID FROM playerdetails WHERE Alias = "Chad Muse"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Jonas Neubauer"),2,(SELECT ID FROM playerdetails WHERE Alias = "Terry Purcell"),0,(SELECT ID FROM playerdetails WHERE Alias = "Jonas Neubauer"),(SELECT ID FROM playerdetails WHERE Alias = "Terry Purcell"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Harry Hong"),2,(SELECT ID FROM playerdetails WHERE Alias = "Matt Buco"),0,(SELECT ID FROM playerdetails WHERE Alias = "Harry Hong"),(SELECT ID FROM playerdetails WHERE Alias = "Matt Buco"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Bo Steil"),1,(SELECT ID FROM playerdetails WHERE Alias = "Quaid"),2,(SELECT ID FROM playerdetails WHERE Alias = "Quaid"),(SELECT ID FROM playerdetails WHERE Alias = "Bo Steil"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),


('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Alex Kerr"),1,(SELECT ID FROM playerdetails WHERE Alias = "Jonas Neubauer"),2,(SELECT ID FROM playerdetails WHERE Alias = "Jonas Neubauer"),(SELECT ID FROM playerdetails WHERE Alias = "Alex Kerr"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),
('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Harry Hong"),0,(SELECT ID FROM playerdetails WHERE Alias = "Quaid"),2,(SELECT ID FROM playerdetails WHERE Alias = "Quaid"),(SELECT ID FROM playerdetails WHERE Alias = "Harry Hong"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false),


('2015-10-17 15:00:00','2015-10-17 8:00:00',-7,5,(SELECT ID FROM playerdetails WHERE Alias = "Jonas Neubauer"),3,(SELECT ID FROM playerdetails WHERE Alias = "Quaid"),1,(SELECT ID FROM playerdetails WHERE Alias = "Jonas Neubauer"),(SELECT ID FROM playerdetails WHERE Alias = "Quaid"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2015'),false)




