INSERT INTO matches (DateTime, Local_Time ,Timezone,BestOf,Player1ID,Player1Score,Player2ID,Player2Score,WinnerID,LoserID,Version,Live,Completed,EventID,Draw)
VALUES

('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Harry Hong"),2,(SELECT ID FROM playerdetails WHERE Alias = "Cameron Eure"),0,(SELECT ID FROM playerdetails WHERE Alias = "Harry"),(SELECT ID FROM playerdetails WHERE Alias = "Cameron"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Jake Stein"),0,(SELECT ID FROM playerdetails WHERE Alias = "Chad Muse"),2,(SELECT ID FROM playerdetails WHERE Alias = "Chad"),(SELECT ID FROM playerdetails WHERE Alias = "Jake"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Terry Purcell"),2,(SELECT ID FROM playerdetails WHERE Alias = "Gin Morgan"),0,(SELECT ID FROM playerdetails WHERE Alias = "Terry"),(SELECT ID FROM playerdetails WHERE Alias = "Gin"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Quaid"),2,(SELECT ID FROM playerdetails WHERE Alias = "Adam Cornelius"),0,(SELECT ID FROM playerdetails WHERE Alias = "Quaid"),(SELECT ID FROM playerdetails WHERE Alias = "Adam"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Jeff Moore"),2,(SELECT ID FROM playerdetails WHERE Alias = "Patrick Nyffeller"),0,(SELECT ID FROM playerdetails WHERE Alias = "Jeff"),(SELECT ID FROM playerdetails WHERE Alias = "Robin"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Mike Winzinek"),2,(SELECT ID FROM playerdetails WHERE Alias = "Dana Wilcox"),0,(SELECT ID FROM playerdetails WHERE Alias = "Mike"),(SELECT ID FROM playerdetails WHERE Alias = "Dana"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Brian Pellegrin"),0,(SELECT ID FROM playerdetails WHERE Alias = "Schoolmaster"),2,(SELECT ID FROM playerdetails WHERE Alias = "Schoolmaster"),(SELECT ID FROM playerdetails WHERE Alias = "Brian P"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Jani Herlevi"),2,(SELECT ID FROM playerdetails WHERE Alias = "Vince Clemente"),0,(SELECT ID FROM playerdetails WHERE Alias = "Jani"),(SELECT ID FROM playerdetails WHERE Alias = "Vince"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Koryan"),2,(SELECT ID FROM playerdetails WHERE Alias = "Rigel Pearce"),0,(SELECT ID FROM playerdetails WHERE Alias = "Koryan"),(SELECT ID FROM playerdetails WHERE Alias = "Rigel"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Eli Markstrom"),2,(SELECT ID FROM playerdetails WHERE Alias = "Matt Buco"),0,(SELECT ID FROM playerdetails WHERE Alias = "Eli"),(SELECT ID FROM playerdetails WHERE Alias = "Buco"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Chris Brady"),0,(SELECT ID FROM playerdetails WHERE Alias = "Trey Harrison"),2,(SELECT ID FROM playerdetails WHERE Alias = "Trey"),(SELECT ID FROM playerdetails WHERE Alias = "Chris B"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Bo Steil"),2,(SELECT ID FROM playerdetails WHERE Alias = "Sean Miller"),0,(SELECT ID FROM playerdetails WHERE Alias = "Bo"),(SELECT ID FROM playerdetails WHERE Alias = "Sean"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Jonas Neubauer"),2,(SELECT ID FROM playerdetails WHERE Alias = "Jordan Harrison"),0,(SELECT ID FROM playerdetails WHERE Alias = "Jonas"),(SELECT ID FROM playerdetails WHERE Alias = "Jordan"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Joey"),2,(SELECT ID FROM playerdetails WHERE Alias = "Peter Grisafi"),0,(SELECT ID FROM playerdetails WHERE Alias = "Joey"),(SELECT ID FROM playerdetails WHERE Alias = "Peter"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Ben Mullen"),2,(SELECT ID FROM playerdetails WHERE Alias = "Frank Westphal"),0,(SELECT ID FROM playerdetails WHERE Alias = "Ben"),(SELECT ID FROM playerdetails WHERE Alias = "Frank"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Alex Kerr"),2,(SELECT ID FROM playerdetails WHERE Alias = "Robin Mihara"),0,(SELECT ID FROM playerdetails WHERE Alias = "Alex"),(SELECT ID FROM playerdetails WHERE Alias = "Robin"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),


('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Harry Hong"),2,(SELECT ID FROM playerdetails WHERE Alias = "Chad Muse"),0,(SELECT ID FROM playerdetails WHERE Alias = "Harry"),(SELECT ID FROM playerdetails WHERE Alias = "Chad"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Terry Purcell"),1,(SELECT ID FROM playerdetails WHERE Alias = "Quaid"),2,(SELECT ID FROM playerdetails WHERE Alias = "Quaid"),(SELECT ID FROM playerdetails WHERE Alias = "Terry"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Jeff Moore"),2,(SELECT ID FROM playerdetails WHERE Alias = "Mike Winzinek"),0,(SELECT ID FROM playerdetails WHERE Alias = "Jeff"),(SELECT ID FROM playerdetails WHERE Alias = "Mike"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Schoolmaster"),0,(SELECT ID FROM playerdetails WHERE Alias = "Jani Herlevi"),2,(SELECT ID FROM playerdetails WHERE Alias = "Jani"),(SELECT ID FROM playerdetails WHERE Alias = "Schoolmaster"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Koryan"),2,(SELECT ID FROM playerdetails WHERE Alias = "Eli Markstrom"),1,(SELECT ID FROM playerdetails WHERE Alias = "Koryan"),(SELECT ID FROM playerdetails WHERE Alias = "Eli"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Trey Harrison"),2,(SELECT ID FROM playerdetails WHERE Alias = "Bo Steil"),0,(SELECT ID FROM playerdetails WHERE Alias = "Trey"),(SELECT ID FROM playerdetails WHERE Alias = "Bo"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Jonas Neubauer"),2,(SELECT ID FROM playerdetails WHERE Alias = "Joey"),0,(SELECT ID FROM playerdetails WHERE Alias = "Jonas"),(SELECT ID FROM playerdetails WHERE Alias = "Joey"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Ben Mullen"),0,(SELECT ID FROM playerdetails WHERE Alias = "Alex Kerr"),2,(SELECT ID FROM playerdetails WHERE Alias = "Alex"),(SELECT ID FROM playerdetails WHERE Alias = "Ben"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),


('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Quaid"),0,(SELECT ID FROM playerdetails WHERE Alias = "Harry Hong"),2,(SELECT ID FROM playerdetails WHERE Alias = "Harry"),(SELECT ID FROM playerdetails WHERE Alias = "Quaid"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Jani Herlevi"),0,(SELECT ID FROM playerdetails WHERE Alias = "Jeff Moore"),2,(SELECT ID FROM playerdetails WHERE Alias = "Jeff"),(SELECT ID FROM playerdetails WHERE Alias = "Jani"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Trey Harrison"),1,(SELECT ID FROM playerdetails WHERE Alias = "Koryan"),2,(SELECT ID FROM playerdetails WHERE Alias = "Harry"),(SELECT ID FROM playerdetails WHERE Alias = "Buco"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Jonas Neubauer"),2,(SELECT ID FROM playerdetails WHERE Alias = "Alex Kerr"),1,(SELECT ID FROM playerdetails WHERE Alias = "Jonas"),(SELECT ID FROM playerdetails WHERE Alias = "Alex"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),


('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Jeff Moore"),2,(SELECT ID FROM playerdetails WHERE Alias = "Harry Hong"),1,(SELECT ID FROM playerdetails WHERE Alias = "Jeff"),(SELECT ID FROM playerdetails WHERE Alias = "Harry"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),
('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Jonas Neubauer"),2,(SELECT ID FROM playerdetails WHERE Alias = "Koryan"),0,(SELECT ID FROM playerdetails WHERE Alias = "Jonas"),(SELECT ID FROM playerdetails WHERE Alias = "Koryan"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false),


('2016-10-27 15:00:00','2016-10-27 8:00:00',-7,5,(SELECT ID FROM playerdetails WHERE Alias = "Jeff Moore"),1,(SELECT ID FROM playerdetails WHERE Alias = "Jonas Neubauer"),3,(SELECT ID FROM playerdetails WHERE Alias = "Jonas"),(SELECT ID FROM playerdetails WHERE Alias = "Jeff"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2016'),false)




