INSERT INTO matches (DateTime, Local_Time ,Timezone,BestOf,Player1ID,Player1Score,Player2ID,Player2Score,WinnerID,LoserID,Version,Live,Completed,EventID,Draw)
VALUES

('2022-5-11 15:00:00','2022-5-11 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Koryan"),0,(SELECT ID FROM playerdetails WHERE Alias = "Vince Clemente"),0,(SELECT ID FROM playerdetails WHERE Alias = "Joey"),(SELECT ID FROM playerdetails WHERE Alias = "Danny"),"NTSC",false,false,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2017'),false),
('2022-5-11 15:00:00','2022-5-11 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Schoolmaster"),0,(SELECT ID FROM playerdetails WHERE Alias = "Alex Kerr"),0,(SELECT ID FROM playerdetails WHERE Alias = "Chad"),(SELECT ID FROM playerdetails WHERE Alias = "Vince"),"NTSC",false,false,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2017'),false),
('2022-5-11 15:00:00','2022-5-11 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Ben Mullen"),0,(SELECT ID FROM playerdetails WHERE Alias = "Stacy Schierholz"),0,(SELECT ID FROM playerdetails WHERE Alias = "Chris B"),(SELECT ID FROM playerdetails WHERE Alias = "Jason"),"NTSC",false,false,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2017'),false),
('2022-5-11 15:00:00','2022-5-11 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Jani Herlevi"),0,(SELECT ID FROM playerdetails WHERE Alias = "Gin Morgan"),0,(SELECT ID FROM playerdetails WHERE Alias = "Jonas"),(SELECT ID FROM playerdetails WHERE Alias = "Robin"),"NTSC",false,false,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2017'),false),
('2022-5-11 15:00:00','2022-5-11 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Bo Steil"),0,(SELECT ID FROM playerdetails WHERE Alias = "MegaRetroMan"),0,(SELECT ID FROM playerdetails WHERE Alias = "Peter"),(SELECT ID FROM playerdetails WHERE Alias = "Dana"),"NTSC",false,false,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2017'),false),
('2022-5-11 15:00:00','2022-5-11 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Eli Markstrom"),0,(SELECT ID FROM playerdetails WHERE Alias = "SQR"),0,(SELECT ID FROM playerdetails WHERE Alias = "David"),(SELECT ID FROM playerdetails WHERE Alias = "Frank"),"NTSC",false,false,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2017'),false),
('2022-5-11 15:00:00','2022-5-11 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Rigel Pearce"),0,(SELECT ID FROM playerdetails WHERE Alias = "Chris Brady"),0,(SELECT ID FROM playerdetails WHERE Alias = "Terry"),(SELECT ID FROM playerdetails WHERE Alias = "Steve"),"NTSC",false,false,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2017'),false),
('2022-5-11 15:00:00','2022-5-11 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Quaid"),0,(SELECT ID FROM playerdetails WHERE Alias = "Greg Velden"),0,(SELECT ID FROM playerdetails WHERE Alias = "Harry"),(SELECT ID FROM playerdetails WHERE Alias = "Brian"),"NTSC",false,false,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2017'),false),
('2022-5-11 15:00:00','2022-10-11 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Harry Hong"),0,(SELECT ID FROM playerdetails WHERE Alias = "Douglas Arcadi"),0,(SELECT ID FROM playerdetails WHERE Alias = "Harry"),(SELECT ID FROM playerdetails WHERE Alias = "Brian"),"NTSC",false,false,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2017'),false),
('2022-5-11 15:00:00','2022-5-11 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Joey"),0,(SELECT ID FROM playerdetails WHERE Alias = "Peter Grisafi"),0,(SELECT ID FROM playerdetails WHERE Alias = "Mike"),(SELECT ID FROM playerdetails WHERE Alias = "Trey"),"NTSC",false,false,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2017'),false),
('2022-5-11 15:00:00','2022-5-11 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Jeff Moore"),0,(SELECT ID FROM playerdetails WHERE Alias = "Frank Westphal"),0,(SELECT ID FROM playerdetails WHERE Alias = "Buco"),(SELECT ID FROM playerdetails WHERE Alias = "Gin"),"NTSC",false,false,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2017'),false),
('2022-5-11 15:00:00','2022-5-11 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Matt Buco"),0,(SELECT ID FROM playerdetails WHERE Alias = "Robin Mihara"),0,(SELECT ID FROM playerdetails WHERE Alias = "Jeff"),(SELECT ID FROM playerdetails WHERE Alias = "Chris E"),"NTSC",false,false,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2017'),false),
('2022-5-11 15:00:00','2022-5-11 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Jonas Neubauer"),0,(SELECT ID FROM playerdetails WHERE Alias = "Mary Powell"),0,(SELECT ID FROM playerdetails WHERE Alias = "Bo"),(SELECT ID FROM playerdetails WHERE Alias = "Ryan"),"NTSC",false,false,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2017'),false),
('2022-5-11 15:00:00','2022-5-11 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Mike Winzinek"),0,(SELECT ID FROM playerdetails WHERE Alias = "Sean Miller"),0,(SELECT ID FROM playerdetails WHERE Alias = "Schoolmaster"),(SELECT ID FROM playerdetails WHERE Alias = "Cameron"),"NTSC",false,false,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2017'),false),
('2022-5-11 15:00:00','2022-5-11 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Chad Muse"),0,(SELECT ID FROM playerdetails WHERE Alias = "Sam Parry"),0,(SELECT ID FROM playerdetails WHERE Alias = "Jani"),(SELECT ID FROM playerdetails WHERE Alias = "Rigel"),"NTSC",false,true,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2017'),false),
('2022-5-11 15:00:00','2022-5-11 8:00:00',-7,3,(SELECT ID FROM playerdetails WHERE Alias = "Trey Harrison"),0,(SELECT ID FROM playerdetails WHERE Alias = "KevinDDR"),0,(SELECT ID FROM playerdetails WHERE Alias = "Quaid"),(SELECT ID FROM playerdetails WHERE Alias = "Adam"),"NTSC",false,false,(SELECT ID FROM events WHERE Name = 'Classic Tetris World Championships 2017'),false)