INSERT INTO QualifyingScores(EventID,PlayerID,QualifyingScore)
VALUES
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Sean Miller'),597660),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Jordan Harrison'),535735),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Vince Clemente'),569397),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Adam Cornelius'),600820),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Rigel Pearce'),516993),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Patrick Nyffeller'),536992),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Chris Brady'),862321),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Cameron Eure'),498740),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Gin Morgan'),660037),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Frank Westphal'),723180),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Jake Stein'),812256),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Dana Wilcox'),767235),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Matt Buco'),793193),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Brian Pellegrin'),856684),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Robin Mihara'),580950),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Peter Grisafi'),777669),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Joey'),817609),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Bo Steil'),896910),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Chad Muse'),798700),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Ben Mullen'),857876),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Terry Purcell'),882143),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Mike Winzinek'),847683),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Eli Markstrom'),817489),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Schoolmaster'),752529),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Jani Herlevi'),958280),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Quaid'),885251),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Alex Kerr'),931533),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Trey Harrison'),705440),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Koryan'),980464),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Harry Hong'),999999),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Jeff Moore'),964823),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2016'),(SELECT ID FROM playerdetails WHERE Alias = 'Jonas Neubauer'),972651)