INSERT INTO QualifyingScores(EventID,PlayerID,QualifyingScore)
VALUES
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Koryan'),999999),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Harry Hong'),990173),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Jonas Neubauer'),984700),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Bo Steil'),952214),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Quaid'),904573),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Trey Harrison'),892695),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Matt Buco'),884829),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Jani Herlevi'),868480),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Ben Mullen'),866399),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Jeff Moore'),858890),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Chad Muse'),852720),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Chris Brady'),852280),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Eli Markstrom'),839816),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Mike Winzinek'),837307),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Joey'),828314),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Schoolmaster'),816252),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Alex Kerr'),790309),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Peter Grisafi'),779940),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Sean Miller'),743310),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'SQR'),676675),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Rigel Pearce'),645269),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Sam Parry'),635311),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Frank Westphal'),634713),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Schoolmaster'),752529),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Stacy Schierholz'),630004),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Gin Morgan'),625809),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Robin Mihara'),614348),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'KevinDDR'),589075),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Greg Velden'),538695),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'MegaRetroMan'),520358),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Mary Powell'),509616),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Douglas Arcadi'),504443),
((SELECT ID FROM Events WHERE Name ='Classic Tetris World Championships 2017'),(SELECT ID FROM playerdetails WHERE Alias = 'Vince Clemente'),499744)